CREATE TABLE `yellowtree`.`SEARCH`
(
  `idsearch` INT NOT NULL AUTO_INCREMENT ,
  `idmovie` INT NULL ,
  `a` INT NULL ,
  `b` INT NULL ,
  `c` INT NULL ,
  `d` INT NULL ,
  `e` INT NULL ,
  `f` INT NULL ,
  `g` INT NULL ,
  `h` INT NULL ,
  `i` INT NULL ,
  `j` INT NULL ,
  `k` INT NULL ,
  `l` INT NULL ,
  `m` INT NULL ,
  `n` INT NULL ,
  `o` INT NULL ,
  `p` INT NULL ,
  `q` INT NULL ,
  `r` INT NULL ,
  `s` INT NULL ,
  `t` INT NULL ,
  `u` INT NULL ,
  `v` INT NULL ,
  `w` INT NULL ,
  `x` INT NULL ,
  `y` INT NULL ,
  `z` INT NULL ,
  `0` INT NULL ,
  `1` INT NULL ,
  `2` INT NULL ,
  `3` INT NULL ,
  `4` INT NULL ,
  `5` INT NULL ,
  `6` INT NULL ,
  `7` INT NULL ,
  `8` INT NULL ,
  `9` INT NULL ,
  `sum` INT NULL ,
  PRIMARY KEY (`idsearch`),
  FOREIGN KEY (`idmovie`) REFERENCES MOVIE(idmovie)
  ) ENGINE = InnoDB;
